#pragma once

#define COMPONENT_TYPE_INVALID			0
#define COMPONENT_TYPE_GAMELOGIC		1
#define COMPONENT_TYPE_TRANSFORM2D		2
#define COMPONENT_TYPE_TRANSFORM3D		3
#define COMPONENT_TYPE_CAMERA2D			4
#define COMPONENT_TYPE_CAMERA3D			5
#define COMPONENT_TYPE_SPRITE2D			6
#define COMPONENT_TYPE_RENDERABLEMESH	7