
#pragma once


#define NO_ERROR					 1

// SHADER
#define FAILED_TO_READ_VERTEX		-1
#define FAILED_TO_READ_FRAGMENT		-2
#define FAILED_TO_COMPILE			-3
#define FAILED_TO_COMPILE_VERTEX	-4
#define FAILED_TO_COMPILE_FRAGMENT	-5
#define FAILED_TO_CREATE_SHADER		-6
