
#pragma once


#define NO_ERROR					 1

// CONFIGURATION
#define ERROR_UNKNOWN_SYSTEM		-1
#define ERROR_UNKNOWN_CONFIG		-2
#define ERROR_BAD_CONFIG			-3
#define ERROR_CONFIG_WITHOUT_SYS	-4

// SHADER
#define SHADER_INIT_ERROR_NO_RENDERER -1

#define FAILED_TO_READ				-2
#define FAILED_TO_COMPILE			-3
#define FAILED_TO_LINK				-4
#define FAILED_TO_CREATE_SHADER		-5
