if (NEED_GLFW)

	list(APPEND DEPENDENCIES glfw_dep)

    ExternalProject_Add(glfw_dep
		PREFIX ${BE_BASE_DEPENDENCY_DIRECTORY}/glfw
		GIT_REPOSITORY https://github.com/glfw/glfw.git
		UPDATE_COMMAND ""
		CMAKE_ARGS 
			-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
			-DGLFW_BUILD_EXAMPLES=OFF
			-DGLFW_BUILD_TESTS=OFF
		# LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
    )
	#set(GLFW_INCLUDE ${CMAKE_INSTALL_PREFIX}/include)
	#set(GLFW_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}glfw3${CMAKE_STATIC_LIBRARY_SUFFIX})
	message(STATUS "GLFW_INCLUDE='${GLFW_INCLUDE}'")
	message(STATUS "GLEW_LIBRARIES='${GLEW_LIBRARIES}'")
endif()
