

if (NEED_GLM)
	find_package(glm PATHS ${CMAKE_INSTALL_PREFIX}/lib/cmake/glm NO_DEFAULT_PATH)	
	message(STATUS "GLM_INCLUDE_DIRS='${GLM_INCLUDE_DIRS}'")
	
	if (NOT ${GLM_INCLUDE_DIRS} STREQUAL "") # glm does not set GLM_FOUND
		message(STATUS "GLM_FOUND='${GLM_INCLUDE_DIRS}', ${GLM_LIBRARIES}")
	else()
		ExternalProject_Add(glm_dep
		PREFIX ${BE_BASE_DEPENDENCY_DIRECTORY}/glm
		GIT_REPOSITORY https://github.com/g-truc/glm.git
		UPDATE_COMMAND ""
		LOG_DOWNLOAD ON
		CMAKE_ARGS
			-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
			-DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_PREFIX}/include
			-DGLM_TEST_ENABLE=OFF
		)
		#ExternalProject_Get_Property(glm_dep INSTALL_DIR)
		#message(FATAL_ERROR "GLM BUILT, PLEASE RECONFIGURE.")
	endif()
endif()
